name: United Agency
tagline: Social Marketing Solutions
description: Social Marketing Solutions
markdown: redcarpet
pygments: true

url: http://united-agency.co.uk
baseurl: /

exclude: ['bower_components', 'node_modules']