name: United Agency
tagline: Social & Digital Marketing Agency, London
description: Social & Digital Marketing Agency, London
markdown: redcarpet
pygments: true

url: http://united-agency.co.uk
baseurl: /

exclude: ['bower_components', 'node_modules']