name: United Agency
tagline: Social & Digital Marketing Agency, London
description: Social & Digital Marketing Agency, London
markdown: redcarpet
pygments: true

url: http://127.0.0.1:4000
baseurl: /

exclude: ['bower_components', 'node_modules']